### ISSUE TITLE
Just a note...

### ISSUE THREAD

**Issue by Danappelxx** [Zewo/Examples#2]
Hi! I've been following Zewo for a few weeks now and I just wanted to say that you have done an amazing job! There's a huge amount of work put into this and it's amazing how it all comes together so nicely. I think that this is where Swift web development will be, and because of that I want to help! To be honest, I don't even know where to start because there's so much already. Let me know if/where I could be useful.

On a somewhat related note, I recommend you create a Gitter or a Slack so that you can kickstart the process of building a community.

Once again - great job!

**Comment by paulofaria** [comment]
Hey man! Thanks for the kind words! Any help is welcome 😃!!! As a matter of fact I created a slack team yesterday. Tell me your email and I'll send you an invite. I'll set up an auto invite later so other people can join in!

**Comment by Danappelxx** [comment]
Cool! My email is Dan.appel00@gmail.com. I think I'll find something to work on :stuck_out_tongue:
